name: Deploy

on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Pull kubeconfig
      working-directory: terraform
      run: |
        mkdir kubeconf
        echo "$KUBE_CONFIG" > kubeconf.conf
        ls -l kubeconf
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Terraform init
      id: init
      run: terraform init 

    - name: Terraform format
      id: fmt
      run: terraform fmt -check

    - name: Terraform validate
      id: validate
      run: terraform validate

    - name: Terraform plan
      id: plan
      run: terraform plan
 
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
